-- เพิ่มส่วนประกอบให้ครบ 48 รายการ ตามรูประบบเดิม
DELETE FROM kins_erp.master_data WHERE category='composition';
INSERT INTO kins_erp.master_data (category, name) VALUES
('composition','Cotton- 53% & Polyester - 47% Oxford'),
('composition','-'),
('composition','100% Cottion'),
('composition','Cotton 100% Satin 4*1'),
('composition','Cotton 100% Twill 3*1 R'),
('composition','Cotton- 23% & Polyester - 77% Herringbone'),
('composition','Cotton- 62% & Polyester - 38% Dobby check'),
('composition','Cotton- 62% & Polyester - 38% Twill 6*6 R'),
('composition','Cotton- 63% & Polyester - 27% Twill 3*1 R Stripe'),
('composition','Cotton- 63% & Polyester - 37% Dobby'),
('composition','Cotton- 63% & Polyester - 37% Dobby (2)'),
('composition','Cotton- 63% & Polyester - 37% Twill 2*2 L Check'),
('composition','Cotton- 63% & Polyester - 37% Twill 2*2 R Check'),
('composition','Cotton- 63% & Polyester - 37% Twill 3*1 R Stripe'),
('composition','Cotton- 64% & Polyester - 36% Dobby'),
('composition','Cotton- 64% & Polyester - 36% Dobby check'),
('composition','Cotton- 64% & Polyester - 36% Twill 2*2 L Check'),
('composition','Cotton- 64% & Polyester - 36% Twill 2*2 R Check'),
('composition','Cotton- 64% Polyester - 36% & Dobby'),
('composition','Cotton- 65% & Polyester - 35% Dobby Check'),
('composition','Cotton- 65% & Polyester - 35% Twill 3*1 R Stripe'),
('composition','Cotton- 65% & Polyester - 35% Dobby'),
('composition','Cotton- 65% & Polyester - 35% Dobby check'),
('composition','Cotton- 65% & Polyester - 35% Dobby Stripe'),
('composition','Cotton- 65% & Polyester - 35% Plain check'),
('composition','Cotton- 65% & Polyester - 35% Twill 2*1 R Check'),
('composition','Cotton- 65% & Polyester - 35% Twill 2*2 R Check'),
('composition','Cotton- 65% & Polyester - 35% Twill 3*1 R Check'),
('composition','Cotton- 65% & Polyester - 35% Twill 3*1 R Stripe (2)'),
('composition','Cotton- 65% & Polyester - 35% Twill 3*1 R Stripe (3)'),
('composition','Cotton- 66% & Polyester - 34% Dobby check'),
('composition','Cotton- 66% & Polyester - 34% Twill 2*1 R Check'),
('composition','Cotton- 68% & Polyester - 32% Dobby'),
('composition','Cotton- 70% & Polyester - 30% Oxford'),
('composition','Polyester - 20% & Cotton- 80% Plain Stripe'),
('composition','Polyester - 23% & Cotton- 33% Dobby Check'),
('composition','Polyester - 35% & Cotton- 65% Twill 3*1 R Stripe'),
('composition','Polyester - 36% & Cotton- 64% Herringbone'),
('composition','Polyester - 63% & Cotton- 37% Herringbone'),
('composition','Polyester - 65% & Cotton- 35% Seersucker Stipre'),
('composition','Polyester - 77% & Cotton- 23% Twill 2*2 L Check'),
('composition','Polyester - 77% & Cotton- 23% Twill 2*2 R'),
('composition','Polyester - 77% & Cotton- 23% Twill 2*2 R Stripe'),
('composition','Polyester - 77% & Cotton- 23% Dobby'),
('composition','Polyester - 78% & Cotton- 22% Dobby Check'),
('composition','Polyester 36% Cotton 64% Basket'),
('composition','Polyester 36% Cotton 64% Dobby'),
('composition','Polyester 65% Cotton 35% Dobby');
